# Neurona MP



In [ ]:
from sklearn.metrics import accuracy_score
import numpy as np

class MPNeuron:

  def __init__(self, threshold):
    self.threshold = threshold

  def model(self, X): #X las caracteristicas de entrada -> [1,1,0,1]
    return (sum(X) >= self.threshold)

  def predict(self, X): #  [ [1,0,0,1], [1,0,1,1], [1,0,0,0] ]
    predictions = []

    for i in X:
      predictions.append(self.model(i))

    return np.array(predictions)

  def fit(self, X, y): # X_train_bin, y_train
    accuracy = {}

    for i in range(X.shape[1]+1):
      #asignando un valor al threslhod
      self.threshold = i #1

      # llega con algun valor str, revisar!
      predictions = self.predict(X)# se aplican las predicciones a todos los valores de entrenamiento


      #se mide la precision
      accuracy[i] = accuracy_score(y, predictions)

    #se obtiene el mejor threshold
    best_threshold = max(accuracy, key=accuracy.get)
    self.threshold = best_threshold


In [ ]:
modelo = MPNeuron(threshold=3)

modelo.predict([[1,0,0,1], [1,0,0,1,1] ,[1,0,0,0,1,1]])

array([False,  True,  True])

In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd


data_cancer = load_breast_cancer()

df_cancer = pd.DataFrame(data=data_cancer.data, columns=data_cancer.feature_names)

df_cancer

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [ ]:
data_cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, y_test = train_test_split(df_cancer, data_cancer.target, test_size=0.2, random_state=42, stratify=data_cancer.target)

In [ ]:
X_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
546        10.32         16.35           65.31      324.9          0.09434   
432        20.18         19.54          133.80     1250.0          0.11330   
174        10.66         15.15           67.49      349.6          0.08792   
221        13.56         13.90           88.59      561.3          0.10510   
289        11.37         18.89           72.17      396.0          0.08713   
..           ...           ...             ...        ...              ...   
184        15.28         22.41           98.92      710.6          0.09057   
300        19.53         18.90          129.50     1217.0          0.11500   
509        15.46         23.95          103.80      731.3          0.11830   
230        17.05         19.08          113.40      895.0          0.11410   
474        10.88         15.62           70.41      358.9          0.10070   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
546           0.04994         0.01012             0.005495         0.1885   
432           0.14890         0.21330             0.125900         0.1724   
174           0.04302         0.00000             0.000000         0.1928   
221           0.11920         0.07860             0.044510         0.1962   
289           0.05008         0.02399             0.021730         0.2013   
..                ...             ...                  ...            ...   
184           0.10520         0.05375             0.032630         0.1727   
300           0.16420         0.21970             0.106200         0.1792   
509           0.18700         0.20300             0.085200         0.1807   
230           0.15720         0.19100             0.109000         0.2131   
474           0.10690         0.05115             0.015710         0.1861   

     mean fractal dimension  ...  worst radius  worst texture  \
546                 0.06201  ...         11.25          21.77   
432                 0.06053  ...         22.03          25.07   
174                 0.05975  ...         11.54          19.20   
221                 0.06303  ...         14.98          17.13   
289                 0.05955  ...         12.36          26.14   
..                      ...  ...           ...            ...   
184                 0.06317  ...         17.80          28.03   
300                 0.06552  ...         25.93          26.24   
509                 0.07083  ...         17.11          36.33   
230                 0.06325  ...         19.59          24.89   
474                 0.06837  ...         11.94          19.35   

     worst perimeter  worst area  worst smoothness  worst compactness  \
546            71.12       384.9            0.1285            0.08842   
432           146.00      1479.0            0.1665            0.29420   
174            73.20       408.3            0.1076            0.06791   
221           101.10       686.6            0.1376            0.26980   
289            79.29       459.3            0.1118            0.09708   
..               ...         ...               ...                ...   
184           113.80       973.1            0.1301            0.32990   
300           171.10      2053.0            0.1495            0.41160   
509           117.70       909.4            0.1732            0.49670   
230           133.50      1189.0            0.1703            0.39340   
474            80.78       433.1            0.1332            0.38980   

     worst concavity  worst concave points  worst symmetry  \
546          0.04384               0.02381          0.2681   
432          0.53080               0.21730          0.3032   
174          0.00000               0.00000          0.2710   
221          0.25770               0.09090          0.3065   
289          0.07529               0.06203          0.3267   
..               ...                   ...             ...   
184          0.36300               0.12260         

In [ ]:
# transformar los valores de entrenamiento y pruebas a binario
X_train_bin = X_train.apply(pd.cut, bins=2, labels=[1,0]) # antes [0,1]
X_test_bin = X_test.apply(pd.cut, bins=2, labels=[1,0])


In [ ]:
X_test_bin.to_numpy()

array([[0, 0, 0, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=object)

In [ ]:
#Entrenar la neurona
modeloCancer = MPNeuron(1)
modeloCancer.fit(X_train_bin.to_numpy(), Y_train)
modeloCancer.threshold

27

In [ ]:
predicciones = modeloCancer.predict(X_test_bin.to_numpy())

predicciones

array([False,  True, False,  True, False,  True,  True, False, False,
       False,  True, False,  True,  True, False,  True, False, False,
        True, False, False,  True,  True, False, False,  True, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True, False,  True, False,  True,  True,  True, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True, False,  True, False,
        True,  True, False, False,  True, False, False,  True, False,
       False, False, False, False,  True,  True])

In [ ]:
#cual fué la precision de mi modelo
accuracy_score(y_test, predicciones)

0.8157894736842105

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predicciones)

array([[35,  7],
       [14, 58]])

In [ ]:
#Pasos habituales a seguir para entrenar nuestros modelos

# 1. tratar la info, limpiar datos, agrear columnas
# 1.5 Identificar el valor a encontrar (etiqueta)
# 2. Segmentar el conjunto de datos en entrenamiento y pruebas
# 3. Preparar el modelo con los datos (configurar hiperparametros del modelo)
# 4. entrenar el modelo
# 5. hacer predicciones
# 6. evaluar el modelo
# 7. Ajustes al modelo

#Implementarlo en un caso real